name: screen_cast
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Packages ---
  flutter_secure_storage: ^9.2.2
  flutter_webrtc: ^1.2.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  path_provider: ^2.1.3
  permission_handler: ^11.3.1 # <-- ADDED THIS PACKAGE

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true