name: screen_cast
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Updated Package Versions ---
  flutter_secure_storage: ^9.2.2
  flutter_webrtc: ^1.2.0  # <-- Updated version
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  path_provider: ^2.1.3 # <-- Updated version
  # --- End of packages ---

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true